<!DOCTYPE html>
<html lang="en">
<head>

    <style>

        h1
        {
            color: rgb(10, 10, 10);
            text-align:center ;
        }
       body{

           text-align: center;
           background-image:url("../desktop-wallpaper-retrowave-car-chromebook-pixel-background-and.jpg");
           background-size: cover;
       
       }
       form
       {
        text-align: center;
       }
        
       
        
        



    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>BOOK A CAB</h1>
  <h5 style="text-align: center;">Book a Call our Representative Will Call You</h5>
  <hr style="width:100%;text-align:center; size: 4px;">
    <form action="#" onclick="registeruser()">
        <label >NAME:</label>
        <input type="text" id="name"><br><br>
        <label>EMAIL:</label>
        <input type="email" id="email"><br><br>
        <label>PHONE:</label>
        <input type="tel" id="phone" value=><br><br> 
        <label>Time for call:</label>
        <input type="date" id="date"><input type="time" id="time"><br><br>
        <input type="submit" value="Get a Call">


       
    </form>
  
    
<script>
        function registeruser()
        {
            const name=document.getElementById("name").value;
            const email=document.getElementById("email").value;
            const phone=document.getElementById("phone").value;
            const date=document.getElementById("date").value;
            const time=document.getElementById("time").value;
            console.log(name)
            console.log(email)
            console.log(phone)
            console.log(date)
            console.log(time)
          
        }

</script>

</body>
</html>
